/** Demo domain seed: constraints, impacts, alerts, engagements, rewards. */

export const seedConstraints = [
  {
    id: 'cc-dsv5-eu',
    sku: 'Dsv5 VM series',
    resourceType: 'Virtual Machine',
    regions: ['West Europe', 'North Europe'],
    scope: 'Region',
    reportedDate: '2026-07-22T10:00:00Z',
    source: 'Weekly Capacity call',
    severity: 'Critical',
    status: 'Open',
    description:
      'Dsv5 family capacity exhausted in West Europe and North Europe. New deployments and scale-outs blocked until workarounds are confirmed.',
    createdBy: 'u-theo',
    updatedAt: '2026-07-22T10:05:00Z',
    history: [
      {
        id: 'h1',
        at: '2026-07-22T10:00:00Z',
        by: 'u-theo',
        action: 'Created',
        detail: 'Constraint recorded from weekly Capacity call.',
      },
      {
        id: 'h2',
        at: '2026-07-22T10:05:00Z',
        by: 'system',
        action: 'Impact analysis',
        detail: 'Impact analysis completed — 4 customers matched.',
      },
    ],
  },
  {
    id: 'cc-adx-we',
    sku: 'Azure Data Explorer Standard_D14_v2',
    resourceType: 'Azure Data Explorer',
    regions: ['West Europe'],
    scope: 'Region',
    reportedDate: '2026-07-18T14:30:00Z',
    source: 'Capacity team escalation',
    severity: 'High',
    status: 'Under investigation',
    description: 'ADX node SKU constrained in West Europe for new cluster expansions.',
    createdBy: 'u-alex',
    updatedAt: '2026-07-20T09:12:00Z',
    history: [
      {
        id: 'h3',
        at: '2026-07-18T14:30:00Z',
        by: 'u-alex',
        action: 'Created',
        detail: 'Escalation from Capacity team.',
      },
      {
        id: 'h4',
        at: '2026-07-20T09:12:00Z',
        by: 'u-alex',
        action: 'Status update',
        detail: 'Moved to Under investigation.',
      },
    ],
  },
  {
    id: 'cc-sql-ne',
    sku: 'SQL GP_Gen5',
    resourceType: 'Azure Cosmos DB',
    regions: ['North Europe'],
    scope: 'Region',
    reportedDate: '2026-07-10T11:00:00Z',
    source: 'Email thread',
    severity: 'Medium',
    status: 'Mitigating',
    description: 'Intermittent SQL Gen5 capacity pressure in North Europe.',
    createdBy: 'u-maria',
    updatedAt: '2026-07-15T16:40:00Z',
    history: [
      {
        id: 'h5',
        at: '2026-07-10T11:00:00Z',
        by: 'u-maria',
        action: 'Created',
        detail: 'Constraint recorded from email thread.',
      },
      {
        id: 'h6',
        at: '2026-07-15T16:40:00Z',
        by: 'u-maria',
        action: 'Status update',
        detail: 'Workaround path identified with Capacity team.',
      },
    ],
  },
]

export const seedImpacts = [
  {
    id: 'imp1',
    constraintId: 'cc-dsv5-eu',
    customerId: 'c-olympia',
    subscriptionId: 's-olympia-prod',
    region: 'West Europe',
    matchingResourceCount: 2,
    skus: ['Standard_D8s_v5', 'Standard_D16s_v5'],
  },
  {
    id: 'imp2',
    constraintId: 'cc-dsv5-eu',
    customerId: 'c-olympia',
    subscriptionId: 's-olympia-dr',
    region: 'North Europe',
    matchingResourceCount: 1,
    skus: ['Standard_D8s_v5'],
  },
  {
    id: 'imp3',
    constraintId: 'cc-dsv5-eu',
    customerId: 'c-helix',
    subscriptionId: 's-helix-core',
    region: 'West Europe',
    matchingResourceCount: 2,
    skus: ['Standard_D4s_v5', 'Standard_D8s_v5'],
  },
  {
    id: 'imp4',
    constraintId: 'cc-dsv5-eu',
    customerId: 'c-nova',
    subscriptionId: 's-nova-web',
    region: 'North Europe',
    matchingResourceCount: 1,
    skus: ['Standard_D8s_v5'],
  },
  {
    id: 'imp5',
    constraintId: 'cc-dsv5-eu',
    customerId: 'c-summit',
    subscriptionId: 's-summit-ops',
    region: 'North Europe',
    matchingResourceCount: 1,
    skus: ['Standard_D8s_v5'],
  },
  {
    id: 'imp6',
    constraintId: 'cc-adx-we',
    customerId: 'c-aether',
    subscriptionId: 's-aether-analytics',
    region: 'West Europe',
    matchingResourceCount: 1,
    skus: ['Standard_D14_v2'],
  },
  {
    id: 'imp7',
    constraintId: 'cc-sql-ne',
    customerId: 'c-nova',
    subscriptionId: 's-nova-web',
    region: 'North Europe',
    matchingResourceCount: 1,
    skus: ['GP_Gen5_8'],
  },
]

export const seedAlerts = [
  {
    id: 'a1',
    constraintId: 'cc-dsv5-eu',
    customerId: 'c-olympia',
    csaOwnerId: 'u-theo',
    channel: 'In-app',
    title: 'Dsv5 capacity risk — Olympia Bank',
    message:
      'Olympia Bank has 3 Dsv5 resources in West Europe / North Europe exposed to the new capacity constraint.',
    createdAt: '2026-07-22T10:06:00Z',
    read: false,
  },
  {
    id: 'a2',
    constraintId: 'cc-dsv5-eu',
    customerId: 'c-helix',
    csaOwnerId: 'u-theo',
    channel: 'Teams',
    title: 'Dsv5 capacity risk — Helix Manufacturing',
    message: 'Helix Manufacturing has 2 Dsv5 VMs in West Europe at risk.',
    createdAt: '2026-07-22T10:06:00Z',
    read: false,
  },
  {
    id: 'a3',
    constraintId: 'cc-dsv5-eu',
    customerId: 'c-nova',
    csaOwnerId: 'u-maria',
    channel: 'Email',
    title: 'Dsv5 capacity risk — Nova Retail EU',
    message: 'Nova Retail EU has Dsv5 node pool capacity at risk in North Europe.',
    createdAt: '2026-07-22T10:06:00Z',
    read: true,
  },
  {
    id: 'a4',
    constraintId: 'cc-adx-we',
    customerId: 'c-aether',
    csaOwnerId: 'u-maria',
    channel: 'In-app',
    title: 'ADX capacity risk — Aether Health',
    message: 'Aether Health ADX cluster may be unable to expand in West Europe.',
    createdAt: '2026-07-18T14:35:00Z',
    read: true,
  },
]

export const seedEngagements = [
  {
    id: 'e1',
    constraintId: 'cc-sql-ne',
    customerId: 'c-nova',
    initiatedBy: 'u-maria',
    status: 'In progress',
    notes: 'Exploring Gen5 alternative regions and reserved capacity options.',
    createdAt: '2026-07-15T17:00:00Z',
  },
]

export const seedRewards = [
  {
    id: 'rw-seed-1',
    userId: 'u-theo',
    action: 'constraint_created',
    points: 50,
    label: 'Recorded Dsv5 VM series constraint',
    relatedId: 'cc-dsv5-eu',
    createdAt: '2026-07-22T10:00:00Z',
  },
  {
    id: 'rw-seed-2',
    userId: 'u-alex',
    action: 'constraint_created',
    points: 50,
    label: 'Recorded ADX Standard_D14_v2 constraint',
    relatedId: 'cc-adx-we',
    createdAt: '2026-07-18T14:30:00Z',
  },
  {
    id: 'rw-seed-3',
    userId: 'u-maria',
    action: 'constraint_created',
    points: 50,
    label: 'Recorded SQL GP_Gen5 constraint',
    relatedId: 'cc-sql-ne',
    createdAt: '2026-07-10T11:00:00Z',
  },
  {
    id: 'rw-seed-4',
    userId: 'u-maria',
    action: 'engagement_started',
    points: 30,
    label: 'Engaged Capacity for Nova Retail EU',
    relatedId: 'e1',
    createdAt: '2026-07-15T17:00:00Z',
  },
]
