/** Demo seed used once when the database is empty. */
export const seedCustomers = [
  {
    id: 'c-olympia',
    name: 'Olympia Bank',
    tenantId: 'a1b2c3d4-1111-2222-3333-444455556666',
    csaOwnerId: 'u-theo',
    segment: 'Enterprise',
    industry: 'Financial Services',
    regionFocus: ['West Europe', 'North Europe'],
    lastSyncedAt: '2026-07-22T08:15:00Z',
    syncSource: 'Both',
  },
  {
    id: 'c-helix',
    name: 'Helix Manufacturing',
    tenantId: 'b2c3d4e5-2222-3333-4444-555566667777',
    csaOwnerId: 'u-theo',
    segment: 'Enterprise',
    industry: 'Manufacturing',
    regionFocus: ['West Europe'],
    lastSyncedAt: '2026-07-22T07:40:00Z',
    syncSource: 'Both',
  },
  {
    id: 'c-nova',
    name: 'Nova Retail EU',
    tenantId: 'c3d4e5f6-3333-4444-5555-666677778888',
    csaOwnerId: 'u-maria',
    segment: 'Strategic',
    industry: 'Retail',
    regionFocus: ['North Europe', 'Sweden Central'],
    lastSyncedAt: '2026-07-22T06:55:00Z',
    syncSource: 'Customer tenant',
  },
  {
    id: 'c-aether',
    name: 'Aether Health',
    tenantId: 'd4e5f6a7-4444-5555-6666-777788889999',
    csaOwnerId: 'u-maria',
    segment: 'Enterprise',
    industry: 'Healthcare',
    regionFocus: ['West Europe', 'France Central'],
    lastSyncedAt: '2026-07-21T22:10:00Z',
    syncSource: 'Internal system',
  },
  {
    id: 'c-summit',
    name: 'Summit Logistics',
    tenantId: 'e5f6a7b8-5555-6666-7777-888899990000',
    csaOwnerId: 'u-theo',
    segment: 'Corporate',
    industry: 'Logistics',
    regionFocus: ['North Europe'],
    lastSyncedAt: '2026-07-22T09:05:00Z',
    syncSource: 'Both',
  },
]

export const seedSubscriptions = [
  {
    id: 's-olympia-prod',
    customerId: 'c-olympia',
    name: 'Olympia-Prod',
    subscriptionId: '11111111-aaaa-bbbb-cccc-111111111111',
    regions: ['West Europe', 'North Europe'],
  },
  {
    id: 's-olympia-dr',
    customerId: 'c-olympia',
    name: 'Olympia-DR',
    subscriptionId: '11111111-aaaa-bbbb-cccc-222222222222',
    regions: ['North Europe'],
  },
  {
    id: 's-helix-core',
    customerId: 'c-helix',
    name: 'Helix-Core',
    subscriptionId: '22222222-aaaa-bbbb-cccc-111111111111',
    regions: ['West Europe'],
  },
  {
    id: 's-nova-web',
    customerId: 'c-nova',
    name: 'Nova-Web',
    subscriptionId: '33333333-aaaa-bbbb-cccc-111111111111',
    regions: ['North Europe', 'Sweden Central'],
  },
  {
    id: 's-aether-analytics',
    customerId: 'c-aether',
    name: 'Aether-Analytics',
    subscriptionId: '44444444-aaaa-bbbb-cccc-111111111111',
    regions: ['West Europe', 'France Central'],
  },
  {
    id: 's-summit-ops',
    customerId: 'c-summit',
    name: 'Summit-Ops',
    subscriptionId: '55555555-aaaa-bbbb-cccc-111111111111',
    regions: ['North Europe'],
  },
]

export const seedInventory = [
  {
    id: 'i1',
    customerId: 'c-olympia',
    subscriptionId: 's-olympia-prod',
    resourceType: 'Virtual Machine',
    sku: 'Standard_D8s_v5',
    size: 'Dsv5',
    region: 'West Europe',
    resourceGroup: 'rg-olympia-core',
    name: 'vm-payments-01',
    source: 'Customer tenant',
  },
  {
    id: 'i2',
    customerId: 'c-olympia',
    subscriptionId: 's-olympia-prod',
    resourceType: 'Virtual Machine',
    sku: 'Standard_D16s_v5',
    size: 'Dsv5',
    region: 'West Europe',
    resourceGroup: 'rg-olympia-core',
    name: 'vm-payments-02',
    source: 'Customer tenant',
  },
  {
    id: 'i3',
    customerId: 'c-olympia',
    subscriptionId: 's-olympia-dr',
    resourceType: 'Virtual Machine',
    sku: 'Standard_D8s_v5',
    size: 'Dsv5',
    region: 'North Europe',
    resourceGroup: 'rg-olympia-dr',
    name: 'vm-dr-app-01',
    source: 'Internal system',
  },
  {
    id: 'i4',
    customerId: 'c-helix',
    subscriptionId: 's-helix-core',
    resourceType: 'Virtual Machine',
    sku: 'Standard_D4s_v5',
    size: 'Dsv5',
    region: 'West Europe',
    resourceGroup: 'rg-helix-plant',
    name: 'vm-mes-worker',
    source: 'Customer tenant',
  },
  {
    id: 'i9',
    customerId: 'c-summit',
    subscriptionId: 's-summit-ops',
    resourceType: 'Virtual Machine',
    sku: 'Standard_D8s_v5',
    size: 'Dsv5',
    region: 'North Europe',
    resourceGroup: 'rg-summit-fleet',
    name: 'vm-routing-engine',
    source: 'Customer tenant',
  },
]

export const seedQuotas = [
  {
    id: 'q1',
    customerId: 'c-olympia',
    subscriptionId: 's-olympia-prod',
    region: 'West Europe',
    name: 'Standard DSv5 Family vCPUs',
    limit: 64,
    usage: 48,
    unit: 'vCPUs',
    quotaGroup: 'Compute',
    source: 'Demo seed',
  },
  {
    id: 'q2',
    customerId: 'c-olympia',
    subscriptionId: 's-olympia-dr',
    region: 'North Europe',
    name: 'Standard DSv5 Family vCPUs',
    limit: 32,
    usage: 8,
    unit: 'vCPUs',
    quotaGroup: 'Compute',
    source: 'Demo seed',
  },
  {
    id: 'q3',
    customerId: 'c-helix',
    subscriptionId: 's-helix-core',
    region: 'West Europe',
    name: 'Standard DSv5 Family vCPUs',
    limit: 40,
    usage: 28,
    unit: 'vCPUs',
    quotaGroup: 'Compute',
    source: 'Demo seed',
  },
  {
    id: 'q5',
    customerId: 'c-summit',
    subscriptionId: 's-summit-ops',
    region: 'North Europe',
    name: 'Standard DSv5 Family vCPUs',
    limit: 48,
    usage: 16,
    unit: 'vCPUs',
    quotaGroup: 'Compute',
    source: 'Demo seed',
  },
  {
    id: 'q7',
    customerId: 'c-olympia',
    subscriptionId: 's-olympia-prod',
    region: 'West Europe',
    name: 'Storage Accounts',
    limit: 250,
    usage: 42,
    unit: 'Count',
    quotaGroup: 'Storage',
    source: 'Demo seed',
  },
  {
    id: 'q8',
    customerId: 'c-helix',
    subscriptionId: 's-helix-core',
    region: 'West Europe',
    name: 'Flexible Servers',
    limit: 50,
    usage: 12,
    unit: 'Count',
    quotaGroup: 'Azure PostgreSQL',
    source: 'Demo seed',
  },
  {
    id: 'q9',
    customerId: 'c-nova',
    subscriptionId: 's-nova-web',
    region: 'West Europe',
    name: 'Managed Environments',
    limit: 20,
    usage: 5,
    unit: 'Count',
    quotaGroup: 'Azure Container Apps',
    source: 'Demo seed',
  },
]

/** Azure Quota Groups — shared pools across subscriptions under a management group. */
export const seedQuotaGroupLimits = [
  {
    id: 'qg-olympia-compute-we',
    customerId: 'c-olympia',
    tenantId: 'a1b2c3d4-1111-2222-3333-444455556666',
    managementGroupId: 'mg-olympia-prod',
    groupQuotaName: 'olympiacompute',
    groupDisplayName: 'Olympia Compute Pool',
    subscriptionIds: [
      '11111111-aaaa-bbbb-cccc-111111111111',
      '11111111-aaaa-bbbb-cccc-222222222222',
    ],
    region: 'westeurope',
    name: 'Standard DSv5 Family vCPUs',
    nameValue: 'standardDSv5Family',
    limit: 96,
    availableLimit: 24,
    allocated: 72,
    unit: 'vCPUs',
    resourceProvider: 'Microsoft.Compute',
    source: 'Demo seed',
  },
  {
    id: 'qg-olympia-compute-ne',
    customerId: 'c-olympia',
    tenantId: 'a1b2c3d4-1111-2222-3333-444455556666',
    managementGroupId: 'mg-olympia-prod',
    groupQuotaName: 'olympiacompute',
    groupDisplayName: 'Olympia Compute Pool',
    subscriptionIds: [
      '11111111-aaaa-bbbb-cccc-111111111111',
      '11111111-aaaa-bbbb-cccc-222222222222',
    ],
    region: 'northeurope',
    name: 'Standard DSv5 Family vCPUs',
    nameValue: 'standardDSv5Family',
    limit: 40,
    availableLimit: 8,
    allocated: 32,
    unit: 'vCPUs',
    resourceProvider: 'Microsoft.Compute',
    source: 'Demo seed',
  },
  {
    id: 'qg-helix-compute-we',
    customerId: 'c-helix',
    tenantId: 'b2c3d4e5-2222-3333-4444-555566667777',
    managementGroupId: 'mg-helix-platform',
    groupQuotaName: 'helixcompute',
    groupDisplayName: 'Helix Platform Quota Group',
    subscriptionIds: ['22222222-aaaa-bbbb-cccc-111111111111'],
    region: 'westeurope',
    name: 'Standard DSv5 Family vCPUs',
    nameValue: 'standardDSv5Family',
    limit: 64,
    availableLimit: 36,
    allocated: 28,
    unit: 'vCPUs',
    resourceProvider: 'Microsoft.Compute',
    source: 'Demo seed',
  },
  {
    id: 'qg-summit-compute-ne',
    customerId: 'c-summit',
    tenantId: 'e5f6a7b8-5555-6666-7777-888899990000',
    managementGroupId: 'mg-summit-ops',
    groupQuotaName: 'summitops',
    groupDisplayName: 'Summit Ops Shared Quota',
    subscriptionIds: ['55555555-aaaa-bbbb-cccc-111111111111'],
    region: 'northeurope',
    name: 'Standard DSv5 Family vCPUs',
    nameValue: 'standardDSv5Family',
    limit: 48,
    availableLimit: 32,
    allocated: 16,
    unit: 'vCPUs',
    resourceProvider: 'Microsoft.Compute',
    source: 'Demo seed',
  },
]
